backend:
  name: github
  repo: iorlas/iorlas.com
  branch: main
  use_graphql: true
  # api_root: https://api.github.com
  # base_url: https://api.netlify.com
  # auth_endpoint: auth


media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

collections:
  - name: "kb" # Used in routes, e.g., /admin/collections/blog
    label: "KB Article" # Used in the UI
    folder: "src/content/kb" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      # - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      # - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Is Draft", name: "isDraft", widget: "boolean" } 
      - { label: "Body", name: "body", widget: "markdown" }
